name: Phil Terry
favicon: null
layout_spectrum: 0.1223970428109169
typography_spectrum: 0.4921475755982101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.939840343547985
  lightness: 0.7347635359037668
  saturation: 0.4670127772260457
  rhythmicContrast: 0.8876992401201278
purpose: []
